### ISSUE TITLE
[2 CRASH] Last dev #212

### ISSUE THREAD

**Issue by LDoom** [HerraVp/BleachHack-VpEdition#9]
### 2 crash with the last jar

**_Crash game when starting minecraft:_** 1, with meteor client.

`---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 18/07/21 20:32
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bleachhack'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at bleach.hack.module.mods.Peek.<clinit>(Peek.java:51)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at bleach.hack.module.ModuleManager.loadModules(ModuleManager.java:35)
	at bleach.hack.BleachHack.onInitialize(BleachHack.java:80)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector updateTargetedEntityEntityRayTraceProxy(Lnet/minecraft/class_1297;DFZ)Lnet/minecraft/class_239; in bleachhack.mixins.json:MixinGameRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap bleachhack-vpedition-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 697644832 bytes (665 MiB) / 973078528 bytes (928 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD A6-4400M APU with Radeon(tm) HD Graphics   
	Identifier: AuthenticAMD Family 21 Model 16 Stepping 1
	Microarchitecture: Piledriver
	Frequency (GHz): 2.70
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: AMD Radeon HD 7520G
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x9990
	Graphics card #0 versionInfo: DriverVersion=15.200.1065.0
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 9083.22
	Virtual memory used (MB): 4653.43
	Swap memory total (MB): 1432.96
	Swap memory used (MB): 59.86
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>`

**_In playing_** 2, without meteor client.

`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 18/07/21 20:49
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at bleach.hack.module.mods.UI.drawTargetHUD(UI.java:601)
	at bleach.hack.gui.clickgui.UIClickGuiScreen.lambda$new$26(UIClickGuiScreen.java:92)
	at bleach.hack.gui.clickgui.window.UIWindow.renderUI(UIWindow.java:56)
	at bleach.hack.gui.clickgui.window.UIWindow.render(UIWindow.java:183)
	at bleach.hack.gui.window.WindowScreen.onRenderWindow(WindowScreen.java:107)
	at bleach.hack.gui.window.WindowScreen.method_25394(WindowScreen.java:96)
	at bleach.hack.gui.clickgui.ClickGuiScreen.method_25394(ClickGuiScreen.java:58)
	at bleach.hack.gui.clickgui.UIClickGuiScreen.method_25394(UIClickGuiScreen.java:127)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at bleach.hack.module.mods.UI.drawTargetHUD(UI.java:601)
	at bleach.hack.gui.clickgui.UIClickGuiScreen.lambda$new$26(UIClickGuiScreen.java:92)
	at bleach.hack.gui.clickgui.window.UIWindow.renderUI(UIWindow.java:56)
	at bleach.hack.gui.clickgui.window.UIWindow.render(UIWindow.java:183)
	at bleach.hack.gui.window.WindowScreen.onRenderWindow(WindowScreen.java:107)
	at bleach.hack.gui.window.WindowScreen.method_25394(WindowScreen.java:96)
	at bleach.hack.gui.clickgui.ClickGuiScreen.method_25394(ClickGuiScreen.java:58)
	at bleach.hack.gui.clickgui.UIClickGuiScreen.method_25394(UIClickGuiScreen.java:127)

-- Screen render details --
Details:
	Screen name: bleach.hack.gui.clickgui.UIClickGuiScreen
	Mouse location: Scaled: (63, 320). Absolute: (126.000000, 641.000000)
	Screen size: Scaled: (683, 358). Absolute: (1366, 715). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 2 total; [class_746['Aikla'/13, l='ClientLevel', x=113.05, y=6.00, z=48.04], FakePlayerUtils['NotVp'/72, l='ClientLevel', x=109.92, y=5.00, z=47.31]]
	Chunk stats: 1024, 418
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,112,80), Section: (at 0,0,0 in 4,7,5; chunk contains blocks 64,0,80 to 79,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1491718 game time, 712304179 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Bare_Bones_1.17_Doom, cool.zip, §4§l§o§kaaa§6§l§oCustomTotem§a1.16.2§4§l§o§kaaa.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 677024520 bytes (645 MiB) / 1946157056 bytes (1856 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD A6-4400M APU with Radeon(tm) HD Graphics   
	Identifier: AuthenticAMD Family 21 Model 16 Stepping 1
	Microarchitecture: Piledriver
	Frequency (GHz): 2.70
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: AMD Radeon HD 7520G
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x9990
	Graphics card #0 versionInfo: DriverVersion=15.200.1065.0
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 9083.22
	Virtual memory used (MB): 6260.74
	Swap memory total (MB): 1432.96
	Swap memory used (MB): 209.61
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon HD 7520G GL version 3.2.13399 Core Profile Forward-Compatible Context 15.200.1065.0, ATI Technologies Inc.
	Window size: 1366x715
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Bare_Bones_1.17_Doom, file/cool.zip (incompatible), file/§4§l§o§kaaa§6§l§oCustomTotem§a1.16.2§4§l§o§kaaa.zip (incompatible), Fabric Mods
	Current Language: English (US)
	CPU: 2x AMD A6-4400M APU with Radeon(tm) HD Graphics 
	Player Count: 1 / 8; [class_3222['Aikla'/13, l='ServerLevel[pvp]', x=113.05, y=6.00, z=48.04]]
	Data Packs: vanilla (incompatible), file/oldmechanic-v1-0.zip (incompatible)`

**Comment by HerraVp** [comment]
Does it crash everytime u play?

**Comment by HerraVp** [comment]
It should be fixed now on the latest dev build.

**Comment by LDoom** [comment]
> It should be fixed now on the latest dev build.

It still crashes me, Last dev.
![image](https://user-images.githubusercontent.com/73355762/126175932-012ce7b8-7689-44de-8525-599a4b7f67c2.png)

`---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 19/07/21 09:20
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bleachhack'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at bleach.hack.module.mods.Peek.<clinit>(Peek.java:51)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at bleach.hack.module.ModuleManager.loadModules(ModuleManager.java:35)
	at bleach.hack.BleachHack.onInitialize(BleachHack.java:80)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector updateTargetedEntityEntityRayTraceProxy(Lnet/minecraft/class_1297;DFZ)Lnet/minecraft/class_239; in bleachhack.mixins.json:MixinGameRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap bleachhack-vpedition-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 764100680 bytes (728 MiB) / 1040187392 bytes (992 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD A6-4400M APU with Radeon(tm) HD Graphics   
	Identifier: AuthenticAMD Family 21 Model 16 Stepping 1
	Microarchitecture: Piledriver
	Frequency (GHz): 2.70
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: AMD Radeon HD 7520G
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x9990
	Graphics card #0 versionInfo: DriverVersion=15.200.1065.0
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 9083.22
	Virtual memory used (MB): 4650.41
	Swap memory total (MB): 1432.96
	Swap memory used (MB): 146.92
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>`



**_I thought it was about the TargetHUB._**

starting from this version crashes me:
![image](https://user-images.githubusercontent.com/73355762/126177674-46220f9e-c48e-48b9-b8d8-5190fcaa0285.png)

**Comment by HerraVp** [comment]
Its probably Meteors fault because i've tested everything without Meteor and i didn't crash once.

Or it could be that u almost ran out of memory: `Memory: 764100680 bytes (728 MiB) / 1040187392 bytes (992 MiB)`
So i recommend that u give Minecraft more memory and then see if it doesn't crash anymore.

**Comment by LDoom** [comment]
> Its probably Meteors fault because i've tested everything without Meteor and i didn't crash once.
> 
> Or it could be that u almost ran out of memory: `Memory: 764100680 bytes (728 MiB) / 1040187392 bytes (992 MiB)`
> So i recommend that u give Minecraft more memory and then see if it doesn't crash anymore.

I still think it’s because of the LiquidInteract module, it’s also part of Meteor that maybe there’s no compatibility with the code, they were a good client combo. /:

Sometimes by sodium through rendering or something. 

But the crash involves mentioning BH. :c

_this is different from ram memory:_
Memory: 764100680 bytes (728 MiB) / 1040187392 bytes (992 MiB) up to 2147483648 bytes (2048 MiB)

i use default 2 ram memory.

**Comment by HerraVp** [comment]
I'll try to fix the crash soon.

 And also i dont recommend that u use sodium. Use optifabric instead.
